### ISSUE TITLE
NRLMSISE-00 bug fix

### ISSUE THREAD

**Issue by liamtoney** [ibrewster/homebrew-avo#1]
According to the AVO-G2S README, there's a bug in NRLMSISE-00 that needs to manually fixed: https://github.com/usgs/volcano-avog2s/blob/master/README.md#nrlmsise-00

Might be clunky to do in the formula, and I'm not sure how crucial it is to address (we can ask Hans), but if it's easy to programmatically fix that might be good. Or we could fork the repo, fix bug, and make formula from there?

**Comment by ibrewster** [comment]
Homebrew can apply patches, this sounds like a prime candidate for that (unless this is an actual bug in the original program that should be reported/fixed and submitted back to it). Either way, I can certainly look at figuring out how to get home-brew to apply such a patch though. Shouldn't be all that difficult, as that is a core feature of homebrew.

**Comment by liamtoney** [comment]
Awesome. BTW I tried on my machine and it installed.

**Comment by ibrewster** [comment]
Fixed with commit 67f75df
