### ISSUE TITLE
Brew tries to find unsupported file

### ISSUE THREAD

**Issue by jwbishop** [ibrewster/homebrew-avo#5]
Upon installing Ruby according to the Homebrew install instructions, I received the following error:

liamtoney/homebrew-volcano-ash3d-hourssince does not exist! Run `brew untap liamtoney/homebrew-volcano-ash3d-hourssince` to remove it.

**Comment by ibrewster** [comment]
Did you run the command it indicated `brew untap liamtoney/homebrew-volcano-ash3d-hourssince`? All homebrew formulas have been moved over to my repository at this point, and Liam has removed his, so this error looks like it may be expected. I appears as though you had a previous install in which you had tapped Liam's repository, and this error is simply catching that it no longer is available

**Comment by jwbishop** [comment]
I did run that command. Good to know this is expected behavior.
