### ISSUE TITLE
Brew cannot find **volcano-ash3d-hourssince**

### ISSUE THREAD

**Issue by jwbishop** [ibrewster/homebrew-avo#6]
This is perhaps related to #5. After trying to install **volcano-ash3d-hourssince** from the install instructions
`brew install usgs/volcano-ash3d-hourssince`, the following error is returned:

`Error: No available formula with the name "usgs/volcano-ash3d-hourssince" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.`

**Comment by ibrewster** [comment]
Right. There is no formula usgs/volcano-ash3d-hourssince, as far as I know. There *is* an `ibrewster/avo/hourssince`, however. See directions at https://github.com/ibrewster/homebrew-avo

**Comment by ibrewster** [comment]
Just out of curiosity, where are you seeing `usgs/volcano-ash3d-hourssince`? Perhaps something needs to be updated...

**Comment by jwbishop** [comment]
> Just out of curiosity, where are you seeing `usgs/volcano-ash3d-hourssince`? Perhaps something needs to be updated...

It looks like the README, https://github.com/ibrewster/homebrew-avo.

**Comment by ibrewster** [comment]
Oh, I see the confusion. Those are links to the *repositories* containing the code, not links to the homebrew formula. If you do the tap as specified, you can simply run `brew install <formula name>` to install, where `<formula name>` is the part in bold, not the link underneath it. I'll have to look at clarifying that. Sorry for the confusion!

**Comment by liamtoney** [comment]
Whoops yeah that could be more clear. Maybe adding an example will help. See also https://github.com/usgs/volcano-avog2s/issues/13 over in the AVO-G2S repo. Right now it's not clear that folks can use the Homebrew install method if they're on macOS.

**Comment by ibrewster** [comment]
README updated. Note that I am not a documentation expert, so hopefully it's an improvement :-)

**Comment by jwbishop** [comment]
I think it's much clearer now. Thanks!
